version: "{build}"

image: Visual Studio 2019

skip_tags: true
clone_depth: 1

configuration: Release
platform: Any CPU

before_build:
  - nuget restore Simplify.ProjectsTemplates.sln

build:
  project: Simplify.ProjectsTemplates.sln
  parallel: true
  verbosity: minimal
  publish_nuget: true
